1. Write Python Programs to use various operators in Python

In [1]:
# Addition
num1 = 10
num2 = 5
sum = num1 + num2
print("Sum:", sum)

# Subtraction
num1 = 10
num2 = 5
diff = num1 - num2
print("Difference:", diff)

# Multiplication
num1 = 10
num2 = 5
product = num1 * num2
print("Product:", product)

# Division
num1 = 10
num2 = 5
quotient = num1 / num2
print("Quotient:", quotient)

# Modulus
num1 = 10
num2 = 5
remainder = num1 % num2
print("Remainder:", remainder)

# Exponentiation
num1 = 2
num2 = 3
result = num1 ** num2
print("Result:", result)


Sum: 15
Difference: 5
Product: 50
Quotient: 2.0
Remainder: 0
Result: 8


2. Create list of elements and slice and dice it

In [2]:
# Create a list of elements
my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Slice the list
slice_1 = my_list[2:5]   # Slice from index 2 to index 4 (exclusive)
slice_2 = my_list[:5]    # Slice from the beginning to index 4 (exclusive)
slice_3 = my_list[5:]    # Slice from index 5 to the end
slice_4 = my_list[::2]   # Slice with a step of 2

print("Original List:", my_list)
print("Slice 1:", slice_1)
print("Slice 2:", slice_2)
print("Slice 3:", slice_3)
print("Slice 4:", slice_4)

# Modify the list by dicing
my_list[1:3] = ['a', 'b', 'c']  # Replace elements from index 1 to 2 with new elements

print("Modified List:", my_list)


Original List: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Slice 1: [3, 4, 5]
Slice 2: [1, 2, 3, 4, 5]
Slice 3: [6, 7, 8, 9, 10]
Slice 4: [1, 3, 5, 7, 9]
Modified List: [1, 'a', 'b', 'c', 4, 5, 6, 7, 8, 9, 10]


3. Using while loop accept numbers until sum of numbers is less than 100

In [5]:
# Initialize variables
sum_of_numbers = 0

# Accept numbers until sum is less than 100
while sum_of_numbers < 100:
    num = int(input("Enter a number: "))
    sum_of_numbers += num

print("Sum of numbers exceeded 100. Program terminated.")


Enter a number: 50
Enter a number: 50
Sum of numbers exceeded 100. Program terminated.


4. Write a python program Read & write Excel files 

In [ ]:
import pandas as pd

# Read from Excel file
data = pd.read_excel('input.xlsx', sheet_name='Sheet1')

# Display the data
print("Data read from Excel file:")
print(data)

# Modify the data
data['New Column'] = data['Column 1'] + data['Column 2']

# Write to Excel file
data.to_excel('output.xlsx', index=False, sheet_name='Sheet1')

print("Data written to Excel file.")


5. Write a python program to scrape reviews from a commercial web site

In [10]:
import requests
from bs4 import BeautifulSoup

# URL of the web page containing the reviews
url = "https://www.mouthshut.com/websites/Excelr-com-reviews-926062771"

# Send a GET request to the URL
response = requests.get(url)

# Check if the request was successful
if response.status_code == 200:
    # Parse the HTML content using BeautifulSoup
    soup = BeautifulSoup(response.content, 'html.parser')

    # Find the review elements on the page (modify the selector according to the structure of the web page)
    reviews = soup.select('.review')

    # Extract the text content of each review
    for review in reviews:
        review_text = review.get_text()
        print("Review:", review_text)
else:
    print("Failed to retrieve the web page. Status code:", response.status_code)


6. Create a 3x3 matrix with values ranging from 2 to 10 using numpy

In [12]:
import numpy as np

# Create a 3x3 matrix with values ranging from 2 to 10
matrix = np.arange(2, 11).reshape(3, 3)

# Print the matrix
print(matrix)


[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


7. Write a Python program to convert a list of numeric value into a one-dimensional NumPy array

In [13]:
import numpy as np

# List of numeric values
numeric_list = [2, 4, 6, 8, 10]

# Convert list to one-dimensional NumPy array
array = np.array(numeric_list)

# Print the array
print(array)


[ 2  4  6  8 10]


8. "Write a Python program to create a null vector of size 10 and update sixth value to 11.

In [14]:
import numpy as np

# Create a null vector of size 10
null_vector = np.zeros(10)

# Update the sixth value to 11
null_vector[5] = 11

# Print the null vector
print(null_vector)


[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]
